[profile.release]
opt-level = 3
debug = false
split-debuginfo = '...'
debug-assertions = false
overflow-checks = false
lto = true
panic = 'unwind'
incremental = false
codegen-units = 16

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = '...'
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[workspace]
members = ["config", "exchange-controller", "exchange-stream", "internal-objects", "market-objects", "orderbook", "proto-source", "quoter-errors", "ring-bufer"]
exclude = ["quoter-grpc-server"]
