[package]
name = "orderbook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.8"
tracing = "0.1.37"
rustc-hash = "1.1.0"
async-trait = "0.1.68"
futures = "0.3.28"
ordered-float = "3.7.0"
bounded-vec-deque = "0.1.1"
typed-arena = "2.0.2"
market-object =  { path = "../market-object"}
quoter-errors =  { path = "../quoter-errors"}
